AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
  Exclude:
    - '*_test.rb'

Layout/LineLength:
  Max: 100

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/ClassVars:
  Enabled: false
